Issue-12:added uuid dependency for Bounty Resource Number creation
BanklessDAO/bounty-board pull request #13
Opened 2021-06-21 23:13 UTC by Behold3th

Added uuid dependency through yarn for Bounty Resource Number creation.

2021-06-21 23:48 UTC, amaredeus commented
Hmm I guess we should have posted a CONTRIBUTION.md, generally across open source projects the code merge flows from

main <- develop <- feature/name-of-feature

Here is a good read on this

https://nvie.com/posts/a-successful-git-branching-model/

And there's a good read on git tooling on chapter 3 https://git-scm.com/book/en/v2 but basically we should create a PR from feature/12 -> develop. 

Let me know if you have any questions!

2021-06-21 23:54 UTC, amaredeus requested changes
Please do 

```
git pull origin develop
```

2021-06-22 00:42 UTC, amaredeus requested changes
I think the last change is select "develop"
![chrome_2021-06-21_20-41-53](https://user-images.githubusercontent.com/6130035/122845195-1fe48580-d2d1-11eb-9588-38b1792d6687.png)

2021-06-22 22:14 UTC, Behold3th commented
> I think the last change is select "develop"
> ![chrome_2021-06-21_20-41-53](https://user-images.githubusercontent.com/6130035/122845195-1fe48580-d2d1-11eb-9588-38b1792d6687.png)

should be all set :) thank you!

2021-06-23 00:17 UTC, amaredeus approved these changes

2021-06-23 00:18 UTC, amaredeus commented
Thank you! Everything looks good, feel free to squash and merge

2021-06-25 18:01 UTC, amaredeus requested changes

2021-06-25 18:01 UTC, amaredeus commented on package.json
> +    "dotenv": "^10.0.0",
I'm reading up on next.js and it looks this Next.js includes this, so we can remove this https://nextjs.org/docs/basic-features/environment-variables

2021-07-12 19:00 UTC, merged