Front end mock
BanklessDAO/bounty-board pull request #19
Opened 2021-07-13 23:21 UTC by Behold3th

Front end mock built separately with Next.js and then merged in. 

Current functionality includes: 
`Create`, `Remove`, `Update`, and `Describe` functionality. 

WIP: card structure to be changed to better conform with whimsical.

2021-07-14 00:59 UTC, amaredeus requested changes
There is netlify integration as seen in previous PR https://github.com/BanklessDAO/bounty-board/pull/17#issuecomment-877320039 but I'm not seeing it here

@PaulApivat how was netlify integrated?

2021-07-18 00:17 UTC, amaredeus commented
Netlify is now integrated as part of #23

2021-07-18 00:23 UTC, amaredeus requested changes
Pretty much the source code files should be placed in then we react-app directory and that should trigger the yarn build correctly

2021-07-18 00:23 UTC, amaredeus commented on components/Form.js
> +import { useState } from 'react'
This file should be moved under packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on css/form.css
> +form {
This file should be moved under packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on css/style.css
> +@import url('https://fonts.googleapis.com/css?family=Open+Sans&display=swap');
Going to paste the directly the files should be moved under packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on models/Bounty.js
> +const BountyBoardSchema = new mongoose.Schema({
Going to paste the directly the files should be moved under packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on models/Bounty.js
> +import mongoose from 'mongoose'
Can we use mongodb instead of mongoose?

2021-07-18 00:23 UTC, amaredeus commented on package.json
> -  "private": true,
Can this file be reverted to what we have in develop?

2021-07-18 00:23 UTC, amaredeus commented on pages/[id]/edit.js
> +import { useRouter } from 'next/router'
packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on pages/[id]/index.js
> +import { useState } from 'react'
packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on pages/_app.js
> +import '../css/style.css'
packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on pages/api/bounties/[id].js
> +import dbConnect from '../../../utils/dbConnect'
packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on pages/api/bounties/index.js
> +import dbConnect from '../../../utils/dbConnect'
packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on pages/index.js
> +import Link from 'next/link'
packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on pages/new.js
> +import Form from '../components/Form'
packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on public/zeit.svg
> +<svg width="82" height="16" fill="none" xmlns="http://www.w3.org/2000/svg">
packages/react-app/src

2021-07-18 00:23 UTC, amaredeus commented on utils/dbConnect.js
> +import mongoose from 'mongoose'
packages/react-app/src

2021-07-29 20:51 UTC, Oktalize commented
@Behold3th per our discussion is it okay if we close this PR. We can work on my new branch instead now that i've merged in your changes with it?

2021-08-02 02:11 UTC, Behold3th commented
> @Behold3th per our discussion is it okay if we close this PR. We can work on my new branch instead now that i've merged in your changes with it?

yep, all good!

2021-08-02 02:11 UTC, closed without merging